version: "3.8"

services:
  postgre:
    image: postgres:14.9-alpine3.18
    container_name: postgre
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
  redis:
    image: redis:alpine3.18
    container_name: redis
    ports:
      - "6378:6379"
  backend:
    image: cc-auth:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgre
      - redis
    ports:
      - "9999:9999"
